import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

// The 'geist' package exports them as NextFontWithVariable instances,
// so you can use them directly with their 'variable' property.
const geistSans = GeistSans; // Directly assign the imported font
const geistMono = GeistMono; // Directly assign the imported font

import Navbar from "../components/Navbar.jsx"; // Import the Navbar component

export const metadata = {
    title: "tic-tac-toe",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar className="h-[15vh] w-full"/>
                <main className="flex-1 overflow-y-auto">{children}</main>
            </body>
        </html>
    );
}
